### ISSUE TITLE
consider using optimized fork

### ISSUE THREAD

**Issue by nivekuil** [AshleyYakeley/stable-diffusion-rocm#3]
Hey, thanks for making this. I made one change for my own use, pointing to https://github.com/basujindal/stable-diffusion instead of your fork. This one also does not have the watermark/safety check and runs on less VRAM, as without it Vega will starve on a 512x512 (with it I can do 1024x512). Not sure of any downsides.

**Comment by AshleyYakeley** [comment]
Done.
